### ISSUE TITLE
Release memchaser 0.7

### ISSUE THREAD

**Issue by whimboo** [mozilla/memchaser#225]
This new release will now fully support Australis builds and the new Addon SDK. It's initial support only for the toolbar but not for buttons or anything else. Those features will be part of the maybe next release.

Tasks to do:
- [x] bump version, and update changelog
- [x] Add 0.7 tag
- [ ] Release to AMO

**Comment by whimboo** [comment]
Added release tag:
https://github.com/mozilla/memchaser/tree/0.7

I'm going to upload the XPI to AMO now. I will leave this issue open until it has been approved.

**Comment by whimboo** [comment]
Maybe it's not necessary to keep this issue open. If we have to fix something, a new release would have to be done.

New version is up on AMO:
https://addons.mozilla.org/en-US/firefox/addon/memchaser/versions/?page=1#version-0.7

@xabolcs thanks a lot for all your tireless efforts in getting it working again!

**Comment by xabolcs** [comment]
@Squall-Leonhart, this is the issue where version 0.7 was pushed to the AMO queue.
Feel free to install it directly from AMO! See link in @whimboo's previous comment.

**Comment by Squall-Leonhart** [comment]
Thanks,  takes up a bit of screen realestate as a toolbar but i can just toggle it on and off as i see fit.

I had actually been seeing unresponsive script warnings and hangs of the window iwth high cpu load while i had 0.6 running in firefox 39, i only noticed last night that disabling memchaser fixed that,  will test 0.7 and see if the issue is gone.

**Comment by xabolcs** [comment]
> Thanks, takes up a bit of screen realestate as a toolbar but i can just toggle it on and off as i see fit.

Yeah, in the `ui` modules there are no really successor of `widget`. :(
